name: Build SonarCloud Scan

on:
  push:
    branches:
      - "*"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Injecting src into the ws
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with :
            args: >
              -Dsonar.organization=naedri
              -Dsonar.projectKey=Naedri_company-simulation
              -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
