
jobs:
  run-linters:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: cd client && npm install
      - run: cd client && npm run lint